파이썬 및 코랩 기초

입력 및 출력

In [ ]:
# 변수 선언
name = "KNU"
age = 25
height = 175.5

# 여러 변수 출력
print("이름:", name)
print("나이:", age)
print("키:", height)

조건문과 반복문

In [2]:
# 조건문
score = 85

if score >= 90:
    print("A 학점")
elif score >= 80:
    print("B 학점")
else:
    print("C 학점")

# 반복문 (1부터 5까지 출력)
for i in range(1, 6):
    print(i)

B 학점
1
2
3
4
5


자료구조

In [4]:
# 리스트
numbers = [1, 2, 3, 4, 5]
print("리스트:", numbers)

# 튜플
colors = ("red", "green", "blue")
print("튜플:", colors)

# 딕셔너리
person = {"name": "Alice", "age": 30, "city": "New York"}
print("딕셔너리:", person)


리스트: [1, 2, 3, 4, 5]
튜플: ('red', 'green', 'blue')
딕셔너리: {'name': 'Alice', 'age': 30, 'city': 'New York'}


함수 및 모듈

In [5]:
# 함수 정의
def greet(name):
    return "안녕하세요, " + name + "님!"

# 함수 호출
message = greet("Kim")
print(message)

# 모듈 사용
import math
print("원주율:", math.pi)


안녕하세요, Kim님!
원주율: 3.141592653589793


Numpy 기초

In [6]:
import numpy as np

벡터 덧셈

In [7]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

print(arr_a + arr_b)
print(arr_a * 2)


[5 7 9]
[2 4 6]


Matrix 연산

In [8]:
import numpy as np

# 행렬(matrix) 생성
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result_addition = A + B
print("덧셈 결과:\n", result_addition)

result_subtraction = A - B
print("뺄셈 결과:\n", result_subtraction)


덧셈 결과:
 [[ 6  8]
 [10 12]]
뺄셈 결과:
 [[-4 -4]
 [-4 -4]]


곱셈 연산

In [ ]:
result_elementwise = A * B
print("요소별 곱셈 결과:\n", result_elementwise)

result_dot = np.dot(A, B)
print("내적 결과:\n", result_dot)
# 또는
result_dot_alternative = A @ B
print("내적 결과 (alternative):\n", result_dot_alternative)


요소별 곱셈 결과:
 [[ 5 12]
 [21 32]]
내적 결과:
 [[19 22]
 [43 50]]
내적 결과 (alternative):
 [[19 22]
 [43 50]]
